/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MermaidEditorRouteImport } from './routes/mermaid-editor'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdWikiRouteImport } from './routes/projects/$projectId/wiki'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MermaidEditorRoute = MermaidEditorRouteImport.update({
  id: '/mermaid-editor',
  path: '/mermaid-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdWikiRoute = ProjectsProjectIdWikiRouteImport.update({
  id: '/projects/$projectId/wiki',
  path: '/projects/$projectId/wiki',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mermaid-editor': typeof MermaidEditorRoute
  '/wiki': typeof WikiRoute
  '/projects/$projectId/wiki': typeof ProjectsProjectIdWikiRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mermaid-editor': typeof MermaidEditorRoute
  '/wiki': typeof WikiRoute
  '/projects/$projectId/wiki': typeof ProjectsProjectIdWikiRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mermaid-editor': typeof MermaidEditorRoute
  '/wiki': typeof WikiRoute
  '/projects/$projectId/wiki': typeof ProjectsProjectIdWikiRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mermaid-editor'
    | '/wiki'
    | '/projects/$projectId/wiki'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mermaid-editor'
    | '/wiki'
    | '/projects/$projectId/wiki'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/mermaid-editor'
    | '/wiki'
    | '/projects/$projectId/wiki'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MermaidEditorRoute: typeof MermaidEditorRoute
  WikiRoute: typeof WikiRoute
  ProjectsProjectIdWikiRoute: typeof ProjectsProjectIdWikiRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mermaid-editor': {
      id: '/mermaid-editor'
      path: '/mermaid-editor'
      fullPath: '/mermaid-editor'
      preLoaderRoute: typeof MermaidEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/wiki': {
      id: '/projects/$projectId/wiki'
      path: '/projects/$projectId/wiki'
      fullPath: '/projects/$projectId/wiki'
      preLoaderRoute: typeof ProjectsProjectIdWikiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MermaidEditorRoute: MermaidEditorRoute,
  WikiRoute: WikiRoute,
  ProjectsProjectIdWikiRoute: ProjectsProjectIdWikiRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
